# Created using wingetcreate 1.5.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Microsoft.AppInstaller
PackageVersion: 1.21.2721.0
Platform:
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
PackageFamilyName: Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.6.2721/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 820D6708D4AC09EFF314A989A7BBD6567C2A326316A31718072DBC8CECE8856F
  SignatureSha256: 4291AAEFD266A306BE854CA1D942841EB6531B15FE2A9ECD9269AB484A018D41
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.6.2721/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 820D6708D4AC09EFF314A989A7BBD6567C2A326316A31718072DBC8CECE8856F
  SignatureSha256: 4291AAEFD266A306BE854CA1D942841EB6531B15FE2A9ECD9269AB484A018D41
- Architecture: arm
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.6.2721/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 820D6708D4AC09EFF314A989A7BBD6567C2A326316A31718072DBC8CECE8856F
  SignatureSha256: 4291AAEFD266A306BE854CA1D942841EB6531B15FE2A9ECD9269AB484A018D41
- Architecture: arm64
  InstallerUrl: https://github.com/microsoft/winget-cli/releases/download/v1.6.2721/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle
  InstallerSha256: 820D6708D4AC09EFF314A989A7BBD6567C2A326316A31718072DBC8CECE8856F
  SignatureSha256: 4291AAEFD266A306BE854CA1D942841EB6531B15FE2A9ECD9269AB484A018D41
ManifestType: installer
ManifestVersion: 1.5.0
